# Generated by Django 6.0.5 on 2026-05-26 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_table_delete_employe_delete_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student_table',
            new_name='students_table',
        ),
    ]
