# Generated by Django 6.0.5 on 2026-05-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_register_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('resume', models.FileField(upload_to='resume/')),
            ],
        ),
        migrations.DeleteModel(
            name='register_table',
        ),
        migrations.DeleteModel(
            name='students_table',
        ),
    ]
