# Generated by Django 6.0.5 on 2026-05-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_resume_model_delete_register_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='resume_model_vignan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='resume/')),
            ],
        ),
        migrations.DeleteModel(
            name='Resume_model',
        ),
    ]
