# Generated by Django 6.0.5 on 2026-05-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_new_resume_delete_resume_model_vignan'),
    ]

    operations = [
        migrations.CreateModel(
            name='vignan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='resume')),
            ],
        ),
        migrations.DeleteModel(
            name='new_resume',
        ),
    ]
