# Generated by Django 6.0.5 on 2026-05-27 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_vignan_delete_new_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('resume', models.FileField(upload_to='resume')),
            ],
        ),
        migrations.DeleteModel(
            name='vignan',
        ),
    ]
