# Generated by Django 6.0.5 on 2026-05-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_file_model_delete_vignan'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phno', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='file_model',
        ),
    ]
