# Generated by Django 6.0.5 on 2026-05-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_student_delete_file_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='vignan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aphno', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
