# Generated by Django 6.0.5 on 2026-05-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_vignan_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phno', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='vignan',
        ),
    ]
